[workspace]
exclude = ["util/schema-gen", "util/test-gen", "util/schema-index"]
members = ["taplo-lsp", "taplo-cli", "taplo", "lsp-async-stub"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[profile.bench]
lto = true
opt-level = 3
