[workspace]
exclude = ["util/schema-gen", "util/test-gen"]
members = ["taplo-ide", "taplo", "lsp-async-stub"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[profile.bench]
lto = true
